### ISSUE TITLE
`engines` field at package.json

### ISSUE THREAD

**Issue by markelog** [Avaq/momi#4]
Right now it is set to `^5.0.0`, is there any concerns why it might not work on other versions?

**Comment by Avaq** [comment]
This can probably be lowered to `4.0` if we take care that there is no destructuring happening anywhere.

**Comment by markelog** [comment]
ha-ha, I mean the opposite :), right now there is couple projects working with 6.x & 7.x

**Comment by Avaq** [comment]
Oh! Right. Yeah, I don't see any problems changing it to `>=` or whatever!

**Comment by markelog** [comment]
SGTM

**Comment by markelog** [comment]
fyi, because of that we can't use `yarn` (there is probably some workaround though) it seems it's stricter then npm

**Comment by Avaq** [comment]
Fixed in 7faa863a3e19cbebf46b0415dc6e81f40a2c4a25
