### ISSUE TITLE
Feature: Middleware.fromNodeComputation?

### ISSUE THREAD

**Issue by Beanow** [Avaq/momi#8]
Being `f => Middleware.lift(Future.node(f))`
For cases such as https://github.com/Avaq/node-server-skeleton/blob/master/src/bootstrap/http.js#L40

Is that too sugary?

**Comment by Avaq** [comment]
I prefer to leave that up to users:

```js
const middlewareFromNode = compose (Middleware.lift) (Future.node)
```
